# config/mongomapper.yml

options: &options
  parameterize_keys: false

defaults: &defaults
  adapter: mongodb
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  host: localhost
  database: itelejugito_development

test:
  <<: *defaults
  host: localhost
  database: itelejugito_testing

production:
  adapter: mongodb
  host: ds035897.mongolab.com
  database: itele_production
  port: 35897
  username: pandaking
  password: walle1111
